### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by niallobrien** [uptownhr/hackathon-starter-lite#120]
Hi, I know you mentioned that you want to move to Koa (I see the Koa branch), but there doesn't seem to be much activity there. I'm just wondering what the project status is?

Thanks in advance.

**Comment by uptownhr** [comment]
Hi Nial. 

We did move towards koa but reverted back to express. My primary reason for the move to koa was due to the support or async, however this is not fully supported by koa itself. They are waiting on node.js to natively support async/await before switching over. So I am taking the same approach and waiting on native async/await support on node.

With that said, node v7 just released and async/await may be coming in shortly !

**Comment by niallobrien** [comment]
@uptownhr Sounds awesome. So does that mean that the Express version will be deprecated?

**Comment by uptownhr** [comment]
I am undecided at this point because once async is native, it would mean express will also be able to use this as well. outside of async, I'd have to weigh the value koa brings to the table vs express' abundant middleware and support.
